services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - transients-data:/data
    env_file:
      - path: .env
        required: false

volumes:
  transients-data:
