package store

import (
	"database/sql"
	"errors"
	"time"
)

var ErrNotFound = errors.New("track not found")

type Status string

const (
	StatusPending Status = "pending"
	StatusReady   Status = "ready"
	StatusFailed  Status = "failed"
)

type Track struct {
	Slug         string
	ObjectKey    string
	Title        string
	Status       Status
	ContentType  sql.NullString
	SizeBytes    sql.NullInt64
	Downloadable bool
	ExpiresAt    sql.NullTime
	CreatedAt    time.Time
	ReadyAt      sql.NullTime
}

func (t *Track) Expired() bool {
	return t.ExpiresAt.Valid && time.Now().After(t.ExpiresAt.Time)
}

type Store struct {
	db *sql.DB
}

func New(db *sql.DB) *Store {
	return &Store{db: db}
}

// CreatePending inserts a row for a presigned upload that hasn't been
// discovered by the ingest pipeline yet. slug == objectKey for this path.
func (s *Store) CreatePending(slug, objectKey, title string, expiresAt *time.Time, downloadable bool) error {
	_, err := s.db.Exec(
		`INSERT INTO tracks (slug, object_key, title, status, expires_at, downloadable) VALUES (?, ?, ?, ?, ?, ?)`,
		slug, objectKey, title, StatusPending, nullTime(expiresAt), downloadable,
	)
	return err
}

// CreateFromDiscovery inserts a row for a file discovered in R2 with no
// pre-existing pending record (i.e. dropped in via rclone). A fresh random
// slug is generated by the caller; object_key is the actual R2 key/filename.
func (s *Store) CreateFromDiscovery(slug, objectKey, title string) error {
	_, err := s.db.Exec(
		`INSERT INTO tracks (slug, object_key, title, status, expires_at) VALUES (?, ?, ?, ?, NULL)`,
		slug, objectKey, title, StatusPending,
	)
	return err
}

func (s *Store) GetByObjectKey(objectKey string) (*Track, error) {
	return s.scanOne(s.db.QueryRow(
		`SELECT slug, object_key, title, status, content_type, size_bytes, downloadable, expires_at, created_at, ready_at
		 FROM tracks WHERE object_key = ?`, objectKey))
}

func (s *Store) GetBySlug(slug string) (*Track, error) {
	return s.scanOne(s.db.QueryRow(
		`SELECT slug, object_key, title, status, content_type, size_bytes, downloadable, expires_at, created_at, ready_at
		 FROM tracks WHERE slug = ?`, slug))
}

func (s *Store) MarkReady(slug string, contentType string, sizeBytes int64) error {
	_, err := s.db.Exec(
		`UPDATE tracks SET status = ?, content_type = ?, size_bytes = ?, ready_at = CURRENT_TIMESTAMP
		 WHERE slug = ?`,
		StatusReady, contentType, sizeBytes, slug,
	)
	return err
}

func (s *Store) MarkFailed(slug string) error {
	_, err := s.db.Exec(`UPDATE tracks SET status = ? WHERE slug = ?`, StatusFailed, slug)
	return err
}

func (s *Store) UpdateTrack(slug, title string, expiresAt *time.Time, downloadable bool) error {
	res, err := s.db.Exec(
		`UPDATE tracks SET title = ?, expires_at = ?, downloadable = ? WHERE slug = ?`,
		title, nullTime(expiresAt), downloadable, slug,
	)
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *Store) Delete(slug string) error {
	res, err := s.db.Exec(`DELETE FROM tracks WHERE slug = ?`, slug)
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *Store) ListAll() ([]*Track, error) {
	rows, err := s.db.Query(
		`SELECT slug, object_key, title, status, content_type, size_bytes, downloadable, expires_at, created_at, ready_at
		 FROM tracks ORDER BY created_at DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []*Track
	for rows.Next() {
		t, err := s.scanRow(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

type rowScanner interface {
	Scan(dest ...any) error
}

func (s *Store) scanOne(row *sql.Row) (*Track, error) {
	t, err := s.scan(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return t, nil
}

func (s *Store) scanRow(row rowScanner) (*Track, error) {
	return s.scan(row)
}

func (s *Store) scan(row rowScanner) (*Track, error) {
	var t Track
	err := row.Scan(
		&t.Slug, &t.ObjectKey, &t.Title, &t.Status,
		&t.ContentType, &t.SizeBytes, &t.Downloadable, &t.ExpiresAt, &t.CreatedAt, &t.ReadyAt,
	)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func nullTime(t *time.Time) sql.NullTime {
	if t == nil {
		return sql.NullTime{}
	}
	return sql.NullTime{Time: *t, Valid: true}
}
